# Generated by Django 5.0.7 on 2025-12-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_name', models.CharField(max_length=100)),
                ('ads_description', models.TextField()),
                ('ads_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ads_image', models.FileField(blank=True, null=True, upload_to='ads_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.FileField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phonenumber', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=100)),
                ('user_gmail', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
    ]
