# Generated by Django 5.0.7 on 2025-12-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thayeguu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='ads_payment_method',
            field=models.FileField(blank=True, null=True, upload_to='payment_methods/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_payment_method',
            field=models.FileField(blank=True, null=True, upload_to='payment_methods/'),
        ),
    ]
