# Generated by Django 5.0.7 on 2025-12-21 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thayeguu', '0002_ads_ads_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thayeguu.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thayeguu.user')),
            ],
        ),
    ]
